"""baseline schema

Initial Alembic baseline for the Stock backend.

This revision reproduces ``Base.metadata`` (the canonical ORM schema) exactly:
``alembic upgrade head`` on an empty DB yields a schema byte-equal to
``Base.metadata.create_all`` (asserted by tests/test_alembic.py).

Provenance / reconciliation vs the LIVE production DB (verified 2026-06-30
against a copy of /data/utlab/utlab.db):
  * ``memo`` and ``blog_posts`` are declared here as first-class tables.  In the
    legacy ``init_db`` they were created late / via raw ``CREATE TABLE IF NOT
    EXISTS`` due to a model-ordering bug; the baseline fixes their provenance.
  * ``portfolio_snapshot`` carries ``realized_pnl`` + ``cash_balance`` and the
    named composite unique index ``uq_portfolio_snapshot_date_acct``.  Live uses
    an equivalent inline ``UNIQUE(date, account_no)`` constraint (from a raw
    table rebuild) -- functionally identical; prod is reconciled via ``stamp``.
  * ``recommendation`` has a single ``created_at`` (no duplicate); matches live.
  * ``DateTime(timezone=True)`` columns (watchlist, portfolio_analysis) are
    preserved as-is.
  * Existing prod DBs already HAVE this schema, so they are ``stamp``ed (not
    re-created); a few redundant legacy indexes remain in prod but are harmless.

Revision ID: 94982b843fee
Revises:
Create Date: 2026-06-30 23:34:58.002030

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '94982b843fee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('color', sa.String(length=16), server_default='#3B82F6', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_id'), ['id'], unique=False)

    op.create_table('ai_cycle_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_name', sa.String(length=20), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('state_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_cycle_state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_cycle_state_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_cycle_state_session_name'), ['session_name'], unique=False)

    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_settings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_settings_key'), ['key'], unique=True)

    op.create_table('approval_rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_date', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('ruling_party_pct', sa.Float(), nullable=True),
    sa.Column('opposition_party_pct', sa.Float(), nullable=True),
    sa.Column('president_approval_pct', sa.Float(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_rating', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_rating_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_rating_survey_date'), ['survey_date'], unique=False)

    op.create_table('blog_posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('cover_image', sa.String(length=500), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('tags', sa.String(length=1000), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deposit_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_no', sa.String(length=20), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('trde_no', sa.String(length=40), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('remark', sa.String(length=200), nullable=True),
    sa.Column('balance_after', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deposit_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deposit_event_account_no'), ['account_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_deposit_event_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_deposit_event_id'), ['id'], unique=False)

    op.create_table('investment_diary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diary_date', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investment_diary', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investment_diary_diary_date'), ['diary_date'], unique=True)
        batch_op.create_index(batch_op.f('ix_investment_diary_id'), ['id'], unique=False)

    op.create_table('investment_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('event_date', sa.String(length=10), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('pnl_pct', sa.Float(), nullable=True),
    sa.Column('account_no', sa.String(length=32), nullable=True),
    sa.Column('note', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investment_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investment_event_event_date'), ['event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_investment_event_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_investment_event_id'), ['id'], unique=False)

    op.create_table('investment_mark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('google_event_id', sa.String(length=256), nullable=True),
    sa.Column('google_calendar_id', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_event_id')
    )
    with op.batch_alter_table('investment_mark', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investment_mark_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_investment_mark_id'), ['id'], unique=False)

    op.create_table('market_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('change', sa.Float(), nullable=True),
    sa.Column('change_pct', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('market_index', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_index_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_index_symbol'), ['symbol'], unique=True)

    op.create_table('memo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('sector', sa.String(length=64), nullable=True),
    sa.Column('related_stocks', sa.JSON(), nullable=True),
    sa.Column('group_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_url_hash'), ['url_hash'], unique=True)

    op.create_table('political_calendar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('impact_level', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('political_calendar', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_political_calendar_event_date'), ['event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_political_calendar_id'), ['id'], unique=False)

    op.create_table('political_theme_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('party_affiliation', sa.String(length=20), nullable=False),
    sa.Column('theme_reason', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('political_theme_stock', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_political_theme_stock_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_political_theme_stock_ticker'), ['ticker'], unique=False)

    op.create_table('portfolio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('exchange', sa.String(length=32), nullable=True),
    sa.Column('avg_price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('bought_at', sa.DateTime(), nullable=True),
    sa.Column('sector', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=20), server_default='manual', nullable=False),
    sa.Column('account_no', sa.String(length=32), nullable=True),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_ticker'), ['ticker'], unique=False)

    op.create_table('portfolio_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('account_name', sa.String(length=100), nullable=True),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('outlook', sa.String(length=20), nullable=True),
    sa.Column('recommendation', sa.String(length=20), nullable=True),
    sa.Column('short_term_forecast', sa.String(length=2000), nullable=True),
    sa.Column('key_points_json', sa.String(length=3000), nullable=True),
    sa.Column('risks', sa.String(length=1000), nullable=True),
    sa.Column('confidence', sa.String(length=10), nullable=True),
    sa.Column('session_date', sa.String(length=10), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio_analysis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_analysis_id'), ['id'], unique=False)

    op.create_table('portfolio_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('account_no', sa.String(length=32), server_default='TOTAL', nullable=False),
    sa.Column('total_value', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=False),
    sa.Column('pnl_pct', sa.Float(), nullable=False),
    sa.Column('realized_pnl', sa.Float(), server_default='0', nullable=False),
    sa.Column('cash_balance', sa.Float(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio_snapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_snapshot_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_snapshot_id'), ['id'], unique=False)
        batch_op.create_index('uq_portfolio_snapshot_date_acct', ['date', 'account_no'], unique=True)

    op.create_table('recommendation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('sector', sa.String(length=64), nullable=True),
    sa.Column('sector_weight', sa.Float(), nullable=True),
    sa.Column('news_count', sa.Integer(), nullable=True),
    sa.Column('latest_price', sa.Float(), nullable=True),
    sa.Column('change_pct', sa.Float(), nullable=True),
    sa.Column('strength', sa.String(length=20), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('ai_session', sa.String(length=20), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('entry_range_low', sa.Float(), nullable=True),
    sa.Column('entry_range_high', sa.Float(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('target_return_pct', sa.Float(), nullable=True),
    sa.Column('stop_loss_price', sa.Float(), nullable=True),
    sa.Column('stop_loss_pct', sa.Float(), nullable=True),
    sa.Column('technical_summary', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('community_sentiment', sa.Text(), nullable=True),
    sa.Column('political_theme', sa.String(length=20), nullable=True),
    sa.Column('political_weight', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendation_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendation_ticker'), ['ticker'], unique=False)

    op.create_table('stock_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=False),
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_master', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_master_id'), ['id'], unique=False)
        batch_op.create_index('ix_stock_master_name', ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_master_ticker'), ['ticker'], unique=True)

    op.create_table('stock_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_meta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_meta_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_meta_ticker'), ['ticker'], unique=True)

    op.create_table('stock_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('is_summary', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_price', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_price_id'), ['id'], unique=False)
        batch_op.create_index('ix_stock_price_ticker_date', ['ticker', 'date'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('watchlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('memo', sa.String(length=500), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watchlist_id'), ['id'], unique=False)

    op.create_table('calendar_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('google_event_id', sa.String(length=256), nullable=False),
    sa.Column('calendar_id', sa.String(length=256), nullable=False),
    sa.Column('summary', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=512), nullable=True),
    sa.Column('start_dt', sa.DateTime(), nullable=True),
    sa.Column('end_dt', sa.DateTime(), nullable=True),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.Column('recurrence', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('html_link', sa.String(length=1024), nullable=True),
    sa.Column('color_id', sa.String(length=16), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calendar_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendar_event_google_event_id'), ['google_event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_event_id'), ['id'], unique=False)
        batch_op.create_index('ix_calendar_event_start', ['user_id', 'start_dt'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_event_start_dt'), ['start_dt'], unique=False)
        batch_op.create_index('ix_calendar_event_user_google', ['user_id', 'google_event_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_calendar_event_user_id'), ['user_id'], unique=False)

    op.create_table('calendar_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('google_email', sa.String(length=256), nullable=True),
    sa.Column('encrypted_access_token', sa.Text(), nullable=False),
    sa.Column('encrypted_refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(), nullable=True),
    sa.Column('calendar_id', sa.String(length=256), nullable=False),
    sa.Column('sync_token', sa.Text(), nullable=True),
    sa.Column('sync_tokens_json', sa.Text(), nullable=True),
    sa.Column('calendars_json', sa.Text(), nullable=True),
    sa.Column('connected_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calendar_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendar_token_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_token_user_id'), ['user_id'], unique=True)

    op.create_table('calendar_watch_channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.String(length=256), nullable=False),
    sa.Column('resource_id', sa.String(length=256), nullable=True),
    sa.Column('calendar_id', sa.String(length=256), nullable=False),
    sa.Column('expiration', sa.DateTime(), nullable=True),
    sa.Column('webhook_token', sa.String(length=64), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id')
    )
    with op.batch_alter_table('calendar_watch_channel', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendar_watch_channel_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_watch_channel_user_id'), ['user_id'], unique=False)

    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=True),
    sa.Column('birth_date', sa.String(length=10), nullable=True),
    sa.Column('profile_icon', sa.String(length=8), nullable=True),
    sa.Column('job', sa.String(length=64), nullable=True),
    sa.Column('retire_age', sa.Integer(), nullable=True),
    sa.Column('monthly_income_만', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_profile_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_profile_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_profile_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_profile_id'))

    op.drop_table('user_profile')
    with op.batch_alter_table('calendar_watch_channel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendar_watch_channel_user_id'))
        batch_op.drop_index(batch_op.f('ix_calendar_watch_channel_id'))

    op.drop_table('calendar_watch_channel')
    with op.batch_alter_table('calendar_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendar_token_user_id'))
        batch_op.drop_index(batch_op.f('ix_calendar_token_id'))

    op.drop_table('calendar_token')
    with op.batch_alter_table('calendar_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendar_event_user_id'))
        batch_op.drop_index('ix_calendar_event_user_google')
        batch_op.drop_index(batch_op.f('ix_calendar_event_start_dt'))
        batch_op.drop_index('ix_calendar_event_start')
        batch_op.drop_index(batch_op.f('ix_calendar_event_id'))
        batch_op.drop_index(batch_op.f('ix_calendar_event_google_event_id'))

    op.drop_table('calendar_event')
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlist_id'))

    op.drop_table('watchlist')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    with op.batch_alter_table('stock_price', schema=None) as batch_op:
        batch_op.drop_index('ix_stock_price_ticker_date')
        batch_op.drop_index(batch_op.f('ix_stock_price_id'))

    op.drop_table('stock_price')
    with op.batch_alter_table('stock_meta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_meta_ticker'))
        batch_op.drop_index(batch_op.f('ix_stock_meta_id'))

    op.drop_table('stock_meta')
    with op.batch_alter_table('stock_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_master_ticker'))
        batch_op.drop_index('ix_stock_master_name')
        batch_op.drop_index(batch_op.f('ix_stock_master_id'))

    op.drop_table('stock_master')
    with op.batch_alter_table('recommendation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendation_ticker'))
        batch_op.drop_index(batch_op.f('ix_recommendation_id'))

    op.drop_table('recommendation')
    with op.batch_alter_table('portfolio_snapshot', schema=None) as batch_op:
        batch_op.drop_index('uq_portfolio_snapshot_date_acct')
        batch_op.drop_index(batch_op.f('ix_portfolio_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_portfolio_snapshot_date'))

    op.drop_table('portfolio_snapshot')
    with op.batch_alter_table('portfolio_analysis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_analysis_id'))

    op.drop_table('portfolio_analysis')
    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_ticker'))
        batch_op.drop_index(batch_op.f('ix_portfolio_id'))

    op.drop_table('portfolio')
    with op.batch_alter_table('political_theme_stock', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_political_theme_stock_ticker'))
        batch_op.drop_index(batch_op.f('ix_political_theme_stock_id'))

    op.drop_table('political_theme_stock')
    with op.batch_alter_table('political_calendar', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_political_calendar_id'))
        batch_op.drop_index(batch_op.f('ix_political_calendar_event_date'))

    op.drop_table('political_calendar')
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_url_hash'))
        batch_op.drop_index(batch_op.f('ix_news_status'))
        batch_op.drop_index(batch_op.f('ix_news_published_at'))
        batch_op.drop_index(batch_op.f('ix_news_id'))
        batch_op.drop_index(batch_op.f('ix_news_group_id'))

    op.drop_table('news')
    op.drop_table('memo')
    with op.batch_alter_table('market_index', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_index_symbol'))
        batch_op.drop_index(batch_op.f('ix_market_index_id'))

    op.drop_table('market_index')
    with op.batch_alter_table('investment_mark', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investment_mark_id'))
        batch_op.drop_index(batch_op.f('ix_investment_mark_date'))

    op.drop_table('investment_mark')
    with op.batch_alter_table('investment_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investment_event_id'))
        batch_op.drop_index(batch_op.f('ix_investment_event_event_type'))
        batch_op.drop_index(batch_op.f('ix_investment_event_event_date'))

    op.drop_table('investment_event')
    with op.batch_alter_table('investment_diary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investment_diary_id'))
        batch_op.drop_index(batch_op.f('ix_investment_diary_diary_date'))

    op.drop_table('investment_diary')
    with op.batch_alter_table('deposit_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deposit_event_id'))
        batch_op.drop_index(batch_op.f('ix_deposit_event_date'))
        batch_op.drop_index(batch_op.f('ix_deposit_event_account_no'))

    op.drop_table('deposit_event')
    op.drop_table('blog_posts')
    with op.batch_alter_table('approval_rating', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_rating_survey_date'))
        batch_op.drop_index(batch_op.f('ix_approval_rating_id'))

    op.drop_table('approval_rating')
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_settings_key'))
        batch_op.drop_index(batch_op.f('ix_app_settings_id'))

    op.drop_table('app_settings')
    with op.batch_alter_table('ai_cycle_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_cycle_state_session_name'))
        batch_op.drop_index(batch_op.f('ix_ai_cycle_state_id'))

    op.drop_table('ai_cycle_state')
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_id'))

    op.drop_table('account')
    # ### end Alembic commands ###
